### ISSUE TITLE
How is the value of error rate defined? What does it specifically represent, and is there a calculation formula?

### ISSUE THREAD

**Issue by Yanglv-rookie** [hewm2008/fqcheck#5]
Hi, 
  I am interested in your software, and during its usage, I need to keep track of the error rate. However, I do not understand the error rate provided in the fqcheck file. How is the value of error rate defined? What does it specifically represent, and is there a calculation formula?
![image](https://github.com/hewm2008/fqcheck/assets/91933724/9e1bffb6-18f7-4d74-b7c0-173c7f0005e3)

**Comment by hewm2008** [comment]
According to the quality of base sequencing, the maximum likelihood method is used to estimate the overall error rate. The specific core code is as follows

<pre>
	for(int q=0;q < MAX_Q;q++)  {q_err[q]=1.0/(pow((double)10.0,(double)(q*0.1)));}

       for (all base )    
    {
          err+=q_err[q]*qual[q];   
    }


 Error Rate :    (100.0*err)/(base_total)
</pre>

**Comment by Yanglv-rookie** [comment]
Many thanks

**Comment by Yanglv-rookie** [comment]
I have noticed that the error rate array in the source code seems to be inconsistent with the mathematical calculation results. For example, the error rate for Q30 should be 0.001.
![image](https://github.com/hewm2008/fqcheck/assets/91933724/61a96e98-a332-4a0e-8bac-1160e6865955)

**Comment by hewm2008** [comment]
yes ，In theory  Q30 is 0.001 , 
In theory, this formula  is used for initialization. 
       for(int q=0;q < MAX_Q;q++)  {q_err[q]=1.0/(pow((double)10.0,(double)(q*0.1)));}

But the value rewritten later is the result of the previous callsnp experience statistics. That is, the error rate redefined here is the value actually evaluated by the previous test callsnp test,the really  get the  q_err with the Q by call snp.

**Comment by Yanglv-rookie** [comment]
Thank you very much for your reply.
